language: objective-c

matrix:
    include:
      - osx_image: xcode7.2
        env: TRAVIS_SWIFT_VERSION=2.1.1

script:
- xctool -project WildChat-Swift.xcodeproj -scheme WildChat-Swift -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

